### ISSUE TITLE
Table managment rights

### ISSUE THREAD

**Issue by BlackRule** [eScienceCenter/dbWebGen#29]
Isn't it possible to somehow restrict edit ability for some users for some tables? There is login functionality but no right management? Can it be implemmented by user? Maybe in login_success_proc I can define table rights depending on logged in user name?  
I'll probably have write a separate php script which will after login  
1) edit seetings.php of dbwebgen   
2) open and pass login info to real dbwegen  
Or how do I allow certain users to see/edit certain tables For example  
user:Ivan{
meals{view}
hotels{view,edit}
}
user:maria{
meals{view,edit}
hotels{view}
}

**Comment by derntl** [comment]
This is application logic and should be implemented in a plugin function. You can do that using the setting `$LOGIN['initializer_proc']` or `$APP['preprocess_func']` (these are called at the very beginning of processing), sometimes we also do it in `$APP['menu_complete_proc']`, because often the menu items need to be adapted based on user roles as well.

**Comment by BlackRule** [comment]
Why
```
$TABLES = array (
	'accommodations' => array (
		'display_name' => $__arr['Accommodations'],
		'description' => '',
		'item_name' => $__arr['Accommodation'],
		'actions' => $ALL_ACTIONS <- ISN'T ROLE/USER BASED
		'fields' => array (
```
there's no rights config in $TABLES ? I'll try to hide menus concerning creation of elements but I'm afraid consequently, following "add item" near field which is a reference to another table user still will be able to create items and so on...

**Comment by BlackRule** [comment]
Why
```
$TABLES = array (
	'accommodations' => array (
		'display_name' => $__arr['Accommodations'],
		'description' => '',
		'item_name' => $__arr['Accommodation'],
		'actions' => $ALL_ACTIONS <- ISN'T ROLE/USER BASED
		'fields' => array (
```
there's no rights config in $TABLES ? I'll try to hide menus concerning creation of elements but I'm afraid consequently, following "add item" near field which is a reference to another table user still will be able to create items and so on...

**Comment by derntl** [comment]
The answer is in my previous comment. Roles and associated rights are application specific and therefore not part of the global settings. You need to use one of the functions mentioned in my above comment to modify menus and allowed table actions based on the logged-in user with your $RIGHTS array.
