### ISSUE TITLE
bootstrap dependencies

### ISSUE THREAD

**Issue by eczema** [eScienceCenter/dbWebGen#33]
Hi, I would like to know if you agree to include js and css in the project ? 

Indeed, dbWebGen cannot render pages in 'offline' mode. 
New directories /content should be used : 

/dbWebGen/inc/bootstrap/js
          bootstrap.min.js
          jquery.min.js
          select2.min.js
          transliteration.min.js

/dbWebGen/inc/bootstrap/css
          bootstrap.min.css
          select2-bootstrap.css
          select2.min.css
/dbWebGen/inc/fonts
          glyphicons-halflings-regular.ttf
          glyphicons-halflings-regular.woff
          glyphicons-halflings-regular.woff2

**Comment by derntl** [comment]
Yes I've had this on my todo list for some time but did not get around to it yet. At some point it would be good to do this with some package manager like bower, but if you need a quick fix for now it is probably better to manually include those files locally than referencing their remote location

**Comment by eczema** [comment]
I didn't check how your code depend of bootstrap versioning....
But to avoid unnecessary internal call , i guess the project should include bootstrap necessary stuff. 
I can do this change for you...

**Comment by derntl** [comment]
I am not sure about version dependencies. The engine includes the version that was "good" when I started with the project some years ago :-)

**Comment by eczema** [comment]
I will then include statically bootstrap elements 
Ofc, the css option still work for custom style...

Will comit this evening 

As well will purpose usage of plugin in authentication 
So the only user will have to set setting.php with a function ( user, pass ) .
Code will then check : 
 if array -> ...
 else if function call fun(user,pass) 
else // string 
    use table

**Comment by derntl** [comment]
In the recent commit 78ac5e8dc15ff95ff7df7b39f1825d6392e3eb58 I introduced `npm` to handle dependecies - see also the README file. So it should now be able to run offline as well; this excludes the parts that use Google Visualization API, since Google does not allow to store the API locally.
