### ISSUE TITLE
Search-Function does not work properly

### ISSUE THREAD

**Issue by Kev03** [eScienceCenter/dbWebGen#4]
Searching related data does not work properly in n-m-relations

**Comment by derntl** [comment]
try to set the `search_string_transformation` setting to `'lower(%s::text)'`

**Comment by Kev03** [comment]
did not work

**Comment by derntl** [comment]
Please try with the most recent version if problem still active. If it is still active, there might be some issue with server side php configuration. It appears to work fine on other machines.

**Comment by FallenChromium** [comment]
I'd like to raise this up as it doesn't work for me either (no records found in any type of search, including FK). I'm using cyryllic symbols by the way, that may be a catch. On which functions\configuration options of PHP server this project relies? Maybe I can find what's wrong with it.

**Comment by derntl** [comment]
The searching by typing in the dropdown boxes in the editing forms relies on the search and transliterated out of the box in select2 (currently we rely on 4.0.6-rc.1). I know it performs well at searching characters with/without diacritics), maybe with cyrillic this requires some fiddling with the select2 options.
