### ISSUE TITLE
Search Function always returns no results

### ISSUE THREAD

**Issue by johnleeming** [eScienceCenter/dbWebGen#44]
This looks like a great program that suits my needs well but I'm finding that all searches return null results.  I have columns of various types - text, fixed length characters and boolean, but all searches return no results.  My postgres log shows lines like:
2019-04-10 19:25:00.539 BST [3831] postgres@cases ERROR:  could not determine data type of parameter $1
2019-04-10 19:25:00.539 BST [3831] postgres@cases STATEMENT:  SELECT COUNT(*) FROM "cases" d WHERE "full_text"::text like concat('%', $1, '%')

I'm using Firefox (but get same issues on Vivaldi) on ubuntu 18.04.02 on an oracle VM.
Postgres is v 10.7
PHP v7.3.3

Any help would be much appreciated

**Comment by derntl** [comment]
In settings.php, what is your value for 'search_string_transformation' in $APP? 

You might have to add an explicit typecast to text there.

**Comment by johnleeming** [comment]
Thanks for the quick response.

The current setting is  'search_string_transformation' => '%s'

What should it be?  I understand CAST in sql but I'm not familiar with PHP

**Comment by derntl** [comment]
`%s` is a case sensitive comparison. You could try `upper(%s::text)` which would should get rid of the cast problem and perform case insensitive search.

**Comment by johnleeming** [comment]
Thanks very much - that works perfectly.
I note that boolean fields are displayed as Yes/No but need to be searched as True/false - this isn't a problem for me but I thought it worth noting.
