### ISSUE TITLE
Charts & SQL query box

### ISSUE THREAD

**Issue by johnleeming** [eScienceCenter/dbWebGen#45]
Apologies if I'm missing something obvious but my installation displays list of records fine and I can search on columns, edit & add records but I can't see any way to access the SQL query box or the charts shown in the screenshots.

Do I need to write some plug-ins in PHP?

**Comment by derntl** [comment]
You need to put the link to the query functionality somewhere. The query editor is available by appending `?mode=query` to the URL. To place a link in a custom menu entry, you could follow the way it is done in the dbWebGen demo repository. See the `demo_menu_complete` function there in https://github.com/eScienceCenter/dbWebGen-demo/blob/master/plugin.php . For your plugin file to be included, you need to register the file in the app settings: `$APP['plugins'] = [ 'plugin.php' ]`
